blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://friskymouse.github.io/
    about: Find out how to use FriskyMouse
  - name: Tutorial
    url: https://friskymouse.github.io/docs/prologue/introduction/
    about: Having trouble with the basics? Check out the tutorial!  